import React, { useState, useEffect, useRef, useCallback, useMemo } from 'react'
import { marked } from 'marked'
import { PublicClientApplication } from '@azure/msal-browser'
import { MsalProvider } from '@azure/msal-react'
import { AuthProvider, useAuth } from './components/AuthContext'
import LoginScreen from './components/LoginScreen'
import UserMenu from './components/UserMenu'
import Navigation from './components/Navigation'
import Modal from './components/Modal'
import AddAccomplishmentForm from './components/AddAccomplishmentForm'
import StorageSettings from './components/StorageSettings'
import SettingsModal from './components/SettingsModal'
import { StorageManager } from './utils/storageManager'
import { msalConfig } from './azureAdConfig.js'
import { openAIClient } from './services/openAIClient'

// Initialize MSAL instance
const msalInstance = new PublicClientApplication(msalConfig);

function TeamPulseApp() {
  const { user, isLoading } = useAuth();
  
  if (isLoading) {
    return (
      <div style={{
        minHeight: '100vh',
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
        backgroundColor: '#f8fafc'
      }}>
        <div style={{
          display: 'flex',
          flexDirection: 'column',
          alignItems: 'center',
          gap: '15px'
        }}>
          <div style={{
            width: '40px',
            height: '40px',
            border: '4px solid #f3f4f6',
            borderTop: '4px solid #3b82f6',
            borderRadius: '50%',
            animation: 'spin 1s linear infinite'
          }}></div>
          <p style={{ color: '#6b7280', margin: 0 }}>Loading...</p>
        </div>
      </div>
    );
  }

  if (!user) {
    return <LoginScreen />;
  }

  return <AuthenticatedApp />;
}

function AuthenticatedApp() {
  // Refs for navigation scrolling
  const formRef = useRef(null);
  const listRef = useRef(null);
  const summaryRef = useRef(null);
  const aiGenerationRef = useRef(null);
  
  // State for form inputs
  const [title, setTitle] = useState('')
  const [date, setDate] = useState(new Date().toISOString().split('T')[0])
  const [category, setCategory] = useState('Feature')
  const [description, setDescription] = useState('')
  const [contributors, setContributors] = useState('')
  
  // State for accomplishments list and filtering
  const [accomplishments, setAccomplishments] = useState([])
  const [startDate, setStartDate] = useState('')
  const [endDate, setEndDate] = useState('')
  const [datePreset, setDatePreset] = useState('all-time') // New state for date presets
  const [searchTerm, setSearchTerm] = useState('')
  const [filteredAccomplishments, setFilteredAccomplishments] = useState([])
  const [summaryText, setSummaryText] = useState('')
  const [isSummaryLoading, setIsSummaryLoading] = useState(false)
  // State for tracking if summary was generated by AI
  const [isAISummary, setIsAISummary] = useState(false) // Track if summary was generated by AI
  const [aiModel, setAiModel] = useState('') // Track which model was used for the summary
  const [selectedModel, setSelectedModel] = useState('gpt-4.1') // Model selection for AI summary (Azure deployment name)
  const [customFormat, setCustomFormat] = useState('') // Optional custom formatting instructions from user
  
  // State for progressive loading
  const [visibleItems, setVisibleItems] = useState(3)
  const [isLoading, setIsLoading] = useState(false)
  const loaderRef = useRef(null)
  
  // State for editing
  const [isEditing, setIsEditing] = useState(false)
  const [editId, setEditId] = useState(null)
  
  // State for delete confirmation
  const [showDeleteConfirm, setShowDeleteConfirm] = useState(false)
  
  // State for modal
  const [showAddModal, setShowAddModal] = useState(false)
  
  // State for settings modal
  const [showSettingsModal, setShowSettingsModal] = useState(false)
  
  // Storage-related state
  const [storageType, setStorageType] = useState('localStorage')
  const [sharedFolderPath, setSharedFolderPath] = useState('')
  const [isSharedFolderConnected, setIsSharedFolderConnected] = useState(false)
  const [isStorageLoading, setIsStorageLoading] = useState(false)
  
  // Initialize storage manager
  const storageManager = useMemo(() => {
    const manager = new StorageManager()
    manager.initialize()
    return manager
  }, [])
  
  // Initialize component - load accomplishments from current storage
  useEffect(() => {
    const loadAccomplishments = async () => {
      try {
        setIsStorageLoading(true)
        const data = await storageManager.loadAccomplishments(storageType, sharedFolderPath)
        setAccomplishments(data)
      } catch (error) {
        console.error('Failed to load accomplishments:', error)
        // Fallback to localStorage
        if (storageType !== 'localStorage') {
          const fallbackData = await storageManager.loadAccomplishments('localStorage')
          setAccomplishments(fallbackData)
        }
      } finally {
        setIsStorageLoading(false)
      }
    }
    
    loadAccomplishments()
  }, [storageType, sharedFolderPath])
  
  // Check shared folder connection status
  useEffect(() => {
    const checkSharedFolderConnection = async () => {
      if (storageType === 'sharedfolder') {
        try {
          const isConnected = await storageManager.checkSharedFolderConnection()
          setIsSharedFolderConnected(isConnected)
        } catch (error) {
          console.error('Shared folder connection check failed:', error)
          setIsSharedFolderConnected(false)
        }
      }
    }
    
    checkSharedFolderConnection()
  }, [storageType])
  
  // Storage management functions
  const handleStorageTypeChange = async (newStorageType) => {
    try {
      setIsStorageLoading(true)
      
      // If switching to shared folder, check if folder is selected
      if (newStorageType === 'sharedfolder') {
        const isConnected = await storageManager.checkSharedFolderConnection()
        if (!isConnected) {
          alert('Please select a shared folder first.')
          return
        }
        setIsSharedFolderConnected(true)
      }
      
      // Migrate data if switching storage types
      if (newStorageType !== storageType) {
        await storageManager.migrateData(storageType, newStorageType, sharedFolderPath)
      }
      
      setStorageType(newStorageType)
    } catch (error) {
      console.error('Failed to change storage type:', error)
      alert('Failed to switch storage type. Please try again.')
    } finally {
      setIsStorageLoading(false)
    }
  }
  
  const handleSharedFolderChange = async (newFolderPath) => {
    try {
      setIsStorageLoading(true)
      
      if (storageType === 'sharedfolder') {
        // Test the new folder path
        const isValid = await storageManager.testSharedFolderConnection()
        if (!isValid) {
          alert('Invalid shared folder path. Please check and try again.')
          return
        }
        
        // Migrate data to new folder if needed
        if (newFolderPath !== sharedFolderPath) {
          await storageManager.migrateData('sharedfolder', 'sharedfolder', sharedFolderPath, newFolderPath)
        }
      }
      
      setSharedFolderPath(newFolderPath)
    } catch (error) {
      console.error('Failed to change shared folder:', error)
      alert('Failed to change shared folder. Please try again.')
    } finally {
      setIsStorageLoading(false)
    }
  }
  
  // Handle folder selection
  const handleFolderSelect = async () => {
    console.log('handleFolderSelect in App.jsx called');
    console.log('showDirectoryPicker supported:', 'showDirectoryPicker' in window);
    
    try {
      if ('showDirectoryPicker' in window) {
        console.log('Calling showDirectoryPicker...');
        const dirHandle = await window.showDirectoryPicker()
        console.log('Directory handle received:', dirHandle);
        
        storageManager.setDirectoryHandle(dirHandle)
        setSharedFolderPath(dirHandle.name)
        setIsSharedFolderConnected(true)
        
        console.log('Folder selected successfully:', dirHandle.name);
        return dirHandle // Return the handle for the component to use
      } else {
        console.error('showDirectoryPicker not supported in this browser');
        alert('Directory selection is not supported in this browser. Please use a modern browser like Chrome or Edge.')
        return null
      }
    } catch (error) {
      if (error.name !== 'AbortError') {
        console.error('Failed to select folder:', error)
        alert('Failed to select folder. Please try again.')
      } else {
        console.log('User cancelled folder selection');
      }
      return null
    }
  }
  
  // Save accomplishments to current storage
  const saveAccomplishments = async (updatedAccomplishments) => {
    try {
      await storageManager.saveAccomplishments(updatedAccomplishments, storageType, sharedFolderPath)
      setAccomplishments(updatedAccomplishments)
    } catch (error) {
      console.error('Failed to save accomplishments:', error)
      alert('Failed to save accomplishments. Please try again.')
    }
  }
  
  // Helper functions for date range calculations
  const formatDateForDisplay = (dateString) => {
    if (!dateString) return ''
    const date = new Date(dateString)
    return date.toLocaleDateString('en-US', { 
      month: 'short', 
      day: 'numeric', 
      year: 'numeric' 
    })
  }
  
  const getQuarterDates = (quarterOffset = 0) => {
    const now = new Date()
    const currentYear = now.getFullYear()
    const currentMonth = now.getMonth() // 0-11
    const currentQuarter = Math.floor(currentMonth / 3) // 0-3
    
    const targetQuarter = currentQuarter + quarterOffset
    const targetYear = currentYear + Math.floor(targetQuarter / 4)
    const normalizedQuarter = ((targetQuarter % 4) + 4) % 4
    
    const startMonth = normalizedQuarter * 3
    const endMonth = startMonth + 2
    
    const startDate = new Date(targetYear, startMonth, 1)
    const endDate = new Date(targetYear, endMonth + 1, 0) // Last day of the quarter
    
    return {
      start: startDate.toISOString().split('T')[0],
      end: endDate.toISOString().split('T')[0]
    }
  }
  
  const getSemesterDates = () => {
    const now = new Date()
    const sixMonthsAgo = new Date(now.getFullYear(), now.getMonth() - 6, now.getDate())
    
    return {
      start: sixMonthsAgo.toISOString().split('T')[0],
      end: now.toISOString().split('T')[0]
    }
  }
  
  // Handle preset date range selection
  const handleDatePresetChange = (preset) => {
    setDatePreset(preset)
    
    switch (preset) {
      case 'current-quarter': {
        const { start, end } = getQuarterDates(0)
        setStartDate(start)
        setEndDate(end)
        break
      }
      case 'last-quarter': {
        const { start, end } = getQuarterDates(-1)
        setStartDate(start)
        setEndDate(end)
        break
      }
      case 'last-semester': {
        const { start, end } = getSemesterDates()
        setStartDate(start)
        setEndDate(end)
        break
      }
      case 'custom':
        // Don't change dates for custom selection
        break
      default:
        // Clear dates for "All Time"
        setStartDate('')
        setEndDate('')
        break
    }
  }
  
  // Update preset when manual date changes occur
  useEffect(() => {
    if (!startDate && !endDate) {
      setDatePreset('all-time')
    } else {
      // Check if current dates match any preset
      const currentQuarter = getQuarterDates(0)
      const lastQuarter = getQuarterDates(-1)
      const lastSemester = getSemesterDates()
      
      if (startDate === currentQuarter.start && endDate === currentQuarter.end) {
        setDatePreset('current-quarter')
      } else if (startDate === lastQuarter.start && endDate === lastQuarter.end) {
        setDatePreset('last-quarter')
      } else if (startDate === lastSemester.start && endDate === lastSemester.end) {
        setDatePreset('last-semester')
      } else {
        setDatePreset('custom')
      }
    }
  }, [startDate, endDate])

  // Update filtered accomplishments when accomplishments or date filters change
  useEffect(() => {
    let filtered = [...accomplishments]
    
    if (startDate) {
      filtered = filtered.filter(acc => acc.date >= startDate)
    }
    
    if (endDate) {
      filtered = filtered.filter(acc => acc.date <= endDate)
    }
    
    if (searchTerm.trim()) {
      const search = searchTerm.toLowerCase().trim()
      filtered = filtered.filter(acc => 
        acc.title.toLowerCase().includes(search) || 
        acc.description.toLowerCase().includes(search) ||
        acc.category.toLowerCase().includes(search)
      )
    }
    
    // Sort by date, newest first
    filtered.sort((a, b) => new Date(b.date) - new Date(a.date))
    
    setFilteredAccomplishments(filtered)
    // Reset visible items when filters change
    setVisibleItems(3)
  }, [accomplishments, startDate, endDate, searchTerm])

  // Setup intersection observer for infinite scrolling
  const handleObserver = useCallback((entries) => {
    const target = entries[0]
    if (target.isIntersecting && !isLoading && visibleItems < filteredAccomplishments.length) {
      setIsLoading(true)
      setTimeout(() => {
        setVisibleItems(prev => Math.min(prev + 3, filteredAccomplishments.length))
        setIsLoading(false)
      }, 500) // Add a small delay to simulate loading
    }
  }, [filteredAccomplishments.length, isLoading, visibleItems])

  // Set up and clean up intersection observer
  useEffect(() => {
    const observer = new IntersectionObserver(handleObserver, { threshold: 0.1 })
    const currentLoaderRef = loaderRef.current
    
    if (currentLoaderRef) {
      observer.observe(currentLoaderRef)
    }
    
    return () => {
      if (currentLoaderRef) {
        observer.unobserve(currentLoaderRef)
      }
    }
  }, [handleObserver])

  // Handle form submission
  const handleSubmit = async (e) => {
    e.preventDefault()
    
    // Validate inputs
    if (!title || !date || !category || !description) {
      alert('All fields are required')
      return
    }
    
    try {
      let updatedAccomplishments
      
      if (isEditing) {
        // Update existing accomplishment
        updatedAccomplishments = accomplishments.map(acc => 
          acc.id === editId ? { ...acc, title, date, category, description, contributors } : acc
        )
        
        // Reset editing state
        setIsEditing(false)
        setEditId(null)
      } else {
        // Create new accomplishment
        const newAccomplishment = {
          id: Date.now().toString(),
          title,
          date,
          category,
          description,
          contributors
        }
        
        updatedAccomplishments = [...accomplishments, newAccomplishment]
      }
      
      // Save to current storage
      await saveAccomplishments(updatedAccomplishments)
      
      // Reset form
      setTitle('')
      setDescription('')
      setCategory('Feature')
      setDate(new Date().toISOString().split('T')[0])
      setContributors('')
      
      // Close modal
      setShowAddModal(false)
    } catch (error) {
      console.error('Failed to save accomplishment:', error)
      alert('Failed to save accomplishment. Please try again.')
    }
  }
  
  // Start editing an accomplishment
  const handleEdit = (acc) => {
    setIsEditing(true)
    setEditId(acc.id)
    setTitle(acc.title)
    setDate(acc.date)
    setCategory(acc.category)
    setDescription(acc.description)
    setContributors(acc.contributors || '')
    
    // Open modal instead of scrolling to form
    setShowAddModal(true)
  }
  
  // Delete an accomplishment
  const handleDelete = async (id) => {
    if (window.confirm('Are you sure you want to delete this accomplishment?')) {
      try {
        const updatedAccomplishments = accomplishments.filter(acc => acc.id !== id)
        await saveAccomplishments(updatedAccomplishments)
      } catch (error) {
        console.error('Failed to delete accomplishment:', error)
        alert('Failed to delete accomplishment. Please try again.')
      }
    }
  }
  
  // Delete all accomplishments
  const handleDeleteAll = () => {
    // Show confirmation modal instead of using window.confirm
    setShowDeleteConfirm(true)
  }
  
  // Confirm deletion of all accomplishments
  const confirmDeleteAll = async () => {
    try {
      await saveAccomplishments([])
      // Reset any filters and clear summary
      setSearchTerm('')
      setSummaryText('')
      // Reset visible items
      setVisibleItems(3)
      // Hide confirmation
      setShowDeleteConfirm(false)
    } catch (error) {
      console.error('Failed to delete all accomplishments:', error)
      alert('Failed to delete all accomplishments. Please try again.')
    }
  }
  
  // Cancel delete all
  const cancelDeleteAll = () => {
    setShowDeleteConfirm(false)
  }
  
  // Cancel editing
  const handleCancelEdit = () => {
    setIsEditing(false)
    setEditId(null)
    setTitle('')
    setDescription('')
    setCategory('Feature')
    setDate(new Date().toISOString().split('T')[0])
    setContributors('')
    setShowAddModal(false)
  }

  // Generate summary from filtered accomplishments
  const generateSummary = async () => {
    if (filteredAccomplishments.length === 0) {
      setSummaryText('No accomplishments to summarize in the selected date range.')
      return
    }
    
    // Group by category
    const categorized = {}
    filteredAccomplishments.forEach(acc => {
      if (!categorized[acc.category]) {
        categorized[acc.category] = []
      }
      categorized[acc.category].push(acc)
    })
    
    // Format date for executive presentation
    const formatDate = (dateString) => {
      const date = new Date(dateString)
      return date.toLocaleDateString('en-US', { 
        year: 'numeric', 
        month: 'long', 
        day: 'numeric' 
      })
    }
    
    // Get date range string
    const getDateRangeString = () => {
      if (startDate && endDate) {
        return `${formatDate(startDate)} to ${formatDate(endDate)}`
      } else if (startDate) {
        return `From ${formatDate(startDate)}`
      } else if (endDate) {
        return `Until ${formatDate(endDate)}`
      } else {
        return 'All Time'
      }
    }
    
    // Prepare data for AI summary
    setIsSummaryLoading(true)
    
    try {
      // Create a JSON representation of accomplishments for the AI
      const accomplishmentsData = filteredAccomplishments.map(acc => ({
        title: acc.title,
        date: formatDate(acc.date),
        category: acc.category,
        description: acc.description,
        contributors: acc.contributors || 'Not specified'
      }))
      
      // Create a prompt for the AI
      let prompt = `
        As an executive summary writer, create a compelling and insightful team accomplishment summary for the period: ${getDateRangeString()}.
        
        Structure the summary as follows:
        
        1. EXECUTIVE OVERVIEW: Start with a brief, high-impact overview highlighting key achievements and their business value. Identify major themes across the accomplishments and their strategic importance.
        
        2. KEY ACCOMPLISHMENTS: Identify the 3-4 most significant accomplishments based on potential business impact. For each one, explain its importance to the organization and any measurable outcomes or future benefits. Include the contributor names when mentioning specific accomplishments.
        
        3. CATEGORY INSIGHTS: Organize achievements by category (${Object.keys(categorized).join(', ')}), highlighting patterns and progress in each area. Go beyond listing tasks to explain how each category contributes to overall business objectives. Recognize key contributors and their impact.
        
        4. STRATEGIC OUTLOOK: End with a forward-looking statement about how these accomplishments position the team for future success, what opportunities they enable, and how they align with broader company goals.
        
        Here are the team accomplishments to summarize:
        ${JSON.stringify(accomplishmentsData, null, 2)}
        
        Format guidelines:
        - Use professional, executive-level language with impactful business terms
        - Focus on outcomes, business value, and strategic importance
        - Adapt your language to the domain (technical, operational, strategic, creative, etc.)
        - Highlight cross-cutting themes and patterns across different accomplishments
        - Use Markdown formatting with appropriate headings, bullet points, and emphasis
        - Keep the summary concise but comprehensive (maximum 1500 tokens)
        - Connect achievements to business objectives and organizational goals
        - Use concrete metrics and business impacts where possible
        - Use better formatting of the text to make it easier to read.`
      
      // Append custom formatting instructions if provided
      if (customFormat && customFormat.trim()) {
        prompt += `
        
        ADDITIONAL FORMATTING PREFERENCES:
        ${customFormat.trim()}
        
        Please incorporate these additional formatting preferences while maintaining the core structure above.`
      }
      
      prompt += '\n      '

      console.log(openAIClient);
      
      // Call backend API to generate enhanced summary using Azure OpenAI with Managed Identity
      const completion = await openAIClient.createChatCompletion({
        messages: [
          { 
            role: "system", 
            content: "You are an expert at creating executive summaries that highlight team accomplishments across any domain or industry in a business context. Focus on business impact, strategic insights, and forward-looking perspectives. Adapt your language and focus to the nature of the accomplishments provided."
          },
          { 
            role: "user", 
            content: prompt
          }
        ],
        model: selectedModel, // Model/deployment name
        temperature: 0.3, // More creative outputs
        max_tokens: 1500, // Ensure complete but concise summary
        presence_penalty: 0.3, // Slightly encourage new topics
        frequency_penalty: 0.3, // Slightly discourage repetition
      })
      
      // Extract the AI-generated summary
      const aiSummary = completion.choices[0].message.content
      
      // Set the summary text
      setSummaryText(aiSummary)
      setIsAISummary(true) // Mark as AI-generated summary
      setAiModel(selectedModel) // Set the model used
    } catch (error) {
      console.error('Error generating AI summary:', error)
      
      // Show more detailed error message in console for debugging
      if (error.status) {
        console.error(`API Error Status: ${error.status}`)
        if (error.details) {
          console.error('Error details:', error.details)
        }
      }
      
      // Show user-friendly error message based on error type
      let errorMessage = 'Could not generate Azure OpenAI summary. Falling back to traditional summary.'
      
      if (error.code === 'insufficient_quota' || error.code === 'quota_exceeded') {
        errorMessage = 'Your Azure OpenAI quota has been exceeded. Falling back to traditional summary.'
      } else if (error.code === 'rate_limit_exceeded') {
        errorMessage = 'Rate limit exceeded for Azure OpenAI API. Try again in a moment. Falling back to traditional summary.'
      } else if (error.code === 'context_length_exceeded') {
        errorMessage = 'The input was too long for Azure OpenAI to process. Try filtering to fewer accomplishments. Falling back to traditional summary.'
      } else if (error.code === 'network_error') {
        errorMessage = 'Network error connecting to the API. Please check your connection and try again. Falling back to traditional summary.'
      }
      
      alert(errorMessage)
      
      // Fallback to traditional summary if AI fails
      generateTraditionalSummary()
    } finally {
      setIsSummaryLoading(false)
    }
  }
  
  // Generate traditional summary (fallback if AI fails)
  const generateTraditionalSummary = () => {
    const categorized = {}
    filteredAccomplishments.forEach(acc => {
      if (!categorized[acc.category]) {
        categorized[acc.category] = []
      }
      categorized[acc.category].push(acc)
    })
    
    // Format date for executive presentation
    const formatDate = (dateString) => {
      const date = new Date(dateString)
      return date.toLocaleDateString('en-US', { 
        year: 'numeric', 
        month: 'long', 
        day: 'numeric' 
      })
    }
    
    // Get date range string
    const getDateRangeString = () => {
      if (startDate && endDate) {
        return `${formatDate(startDate)} to ${formatDate(endDate)}`
      } else if (startDate) {
        return `From ${formatDate(startDate)}`
      } else if (endDate) {
        return `Until ${formatDate(endDate)}`
      } else {
        return 'All Time'
      }
    }
    
    // Build executive summary
    let summary = `# Team Accomplishment Highlights\n\n`
    
    // Add reporting period
    summary += `## Reporting Period: ${getDateRangeString()}\n\n`
    
    // Add executive summary
    summary += `## Executive Summary\n\n`
    summary += `The team has completed ${filteredAccomplishments.length} significant accomplishments during this period. `
    
    // Add category distribution
    const categoryCount = Object.keys(categorized).length
    if (categoryCount > 1) {
      summary += `Work was distributed across ${categoryCount} categories, with primary focus on `
      
      // Find top categories by count
      const topCategories = Object.entries(categorized)
        .sort((a, b) => b[1].length - a[1].length)
        .slice(0, 2)
        .map(([category, items]) => `${category} (${items.length})`)
        .join(' and ')
      
      summary += `${topCategories}.\n\n`
    } else {
      const category = Object.keys(categorized)[0]
      summary += `All efforts were focused on ${category} initiatives.\n\n`
    }
    
    // Add key highlights section - select top 3-5 accomplishments based on most recent
    const topAccomplishments = [...filteredAccomplishments]
      .sort((a, b) => new Date(b.date) - new Date(a.date))
      .slice(0, Math.min(5, filteredAccomplishments.length))
    
    summary += `## Key Highlights\n\n`
    topAccomplishments.forEach(acc => {
      const contributorInfo = acc.contributors ? ` [Contributors: ${acc.contributors}]` : ''
      summary += `* **${acc.title}** (${formatDate(acc.date)})${contributorInfo}: ${acc.description}\n`
    })
    summary += `\n`
    
    // Add detailed accomplishments by category
    summary += `## Detailed Accomplishments by Category\n\n`
    
    // Sort categories by most items first
    const sortedCategories = Object.keys(categorized).sort(
      (a, b) => categorized[b].length - categorized[a].length
    )
    
    sortedCategories.forEach(cat => {
      summary += `### ${cat} (${categorized[cat].length})\n\n`
      // Sort items by date - newest first
      const sortedItems = categorized[cat].sort((a, b) => new Date(b.date) - new Date(a.date))
      sortedItems.forEach(acc => {
        const contributorInfo = acc.contributors ? ` [Contributors: ${acc.contributors}]` : ''
        summary += `* **${acc.title}** (${formatDate(acc.date)})${contributorInfo}: ${acc.description}\n`
      })
      summary += `\n`
    })
    
    // Add closing section with next steps or forward-looking statement
    summary += `## Looking Forward\n\n`
    summary += `The team continues to make strong progress and is well-positioned for upcoming initiatives. `
    summary += `This report highlights our commitment to delivering high-quality results and maintaining team productivity.\n`
    
    setSummaryText(summary)
    setIsAISummary(false) // Mark as traditional summary
    setAiModel('') // Clear model as this is not AI-generated
  }

  // Custom renderer for executive summary styling
  const renderMarkdown = (markdown) => {
    if (!markdown) return ''
    
    // Debug: log the input markdown
    // console.log('Input markdown:', markdown)
    
    try {
      // Use marked with simple configuration
      const html = marked.parse(markdown, {
        breaks: true,
        gfm: true,
      })
      
      // Debug: log the raw HTML
      // console.log('Raw HTML from marked:', html)
      
      // Post-process the HTML to add our custom styles
      const styledHtml = html
        // Style headers
        .replace(/<h1>/g, '<h1 style="color: #1e40af; margin-top: 0; margin-bottom: 1rem; font-size: 1.75rem; font-weight: bold;">')
        .replace(/<h2>/g, '<h2 style="color: #1e3a8a; margin-top: 1.5rem; margin-bottom: 1rem; font-size: 1.4rem; font-weight: bold; border-bottom: 2px solid #e5e7eb; padding-bottom: 0.5rem;">')
        .replace(/<h3>/g, '<h3 style="color: #2563eb; margin-top: 1.25rem; margin-bottom: 0.75rem; font-size: 1.2rem; font-weight: bold;">')
        .replace(/<h4>/g, '<h4 style="color: #3b82f6; margin-top: 1rem; margin-bottom: 0.5rem; font-size: 1.1rem; font-weight: bold;">')
        
        // Style paragraphs
        .replace(/<p>/g, '<p style="margin-bottom: 1rem; line-height: 1.6; color: #374151;">')
        
        // Style lists
        .replace(/<ul>/g, '<ul style="margin-bottom: 1rem; padding-left: 1.5rem; color: #374151; list-style-type: disc;">')
        .replace(/<ol>/g, '<ol style="margin-bottom: 1rem; padding-left: 1.5rem; color: #374151;">')
        .replace(/<li>/g, '<li style="margin-bottom: 0.5rem; line-height: 1.5;">')
        
        // Style strong and emphasis
        .replace(/<strong>/g, '<strong style="font-weight: 700; color: #1f2937;">')
        .replace(/<em>/g, '<em style="font-style: italic; color: #4b5563;">')
        
        // Style code
        .replace(/<code>/g, '<code style="background-color: #f3f4f6; padding: 0.25rem 0.5rem; border-radius: 0.25rem; font-family: \'Courier New\', monospace; font-size: 0.9em; color: #1f2937;">')
        
        // Style blockquotes
        .replace(/<blockquote>/g, '<blockquote style="border-left: 4px solid #3b82f6; padding: 1rem; margin: 1rem 0; font-style: italic; color: #4b5563; background-color: #f8fafc; border-radius: 0.375rem;">')
        
        // Style tables
        .replace(/<table>/g, '<table style="width: 100%; border-collapse: collapse; margin: 1rem 0; border: 1px solid #e5e7eb; border-radius: 0.375rem; overflow: hidden;">')
        .replace(/<th>/g, '<th style="padding: 0.75rem; text-align: left; font-weight: 600; background-color: #f9fafb; color: #374151; border-bottom: 1px solid #e5e7eb;">')
        .replace(/<td>/g, '<td style="padding: 0.75rem; color: #374151; border-bottom: 1px solid #e5e7eb;">')
        .replace(/<tr>/g, '<tr style="border-bottom: 1px solid #e5e7eb;">')
        
        // Style horizontal rules
        .replace(/<hr>/g, '<hr style="border: none; height: 2px; background-color: #e5e7eb; margin: 2rem 0; border-radius: 1px;" />')
      
      // Debug: log the final styled HTML
      console.log('Final styled HTML:', styledHtml)
      
      return styledHtml
        
    } catch (error) {
      console.error('Markdown parsing error:', error)
      // Enhanced fallback with basic formatting
      const fallbackHtml = markdown
        .replace(/\*\*(.*?)\*\*/g, '<strong style="font-weight: 700; color: #1f2937;">$1</strong>')
        .replace(/\*(.*?)\*/g, '<em style="font-style: italic; color: #4b5563;">$1</em>')
        .replace(/^# (.*$)/gm, '<h1 style="color: #1e40af; margin-top: 0; margin-bottom: 1rem; font-size: 1.75rem; font-weight: bold;">$1</h1>')
        .replace(/^## (.*$)/gm, '<h2 style="color: #1e3a8a; margin-top: 1.5rem; margin-bottom: 1rem; font-size: 1.4rem; font-weight: bold; border-bottom: 2px solid #e5e7eb; padding-bottom: 0.5rem;">$1</h2>')
        .replace(/^### (.*$)/gm, '<h3 style="color: #2563eb; margin-top: 1.25rem; margin-bottom: 0.75rem; font-size: 1.2rem; font-weight: bold;">$1</h3>')
        .replace(/^\* (.*$)/gm, '<li style="margin-bottom: 0.5rem; line-height: 1.5; color: #374151;">$1</li>')
        .replace(/\n\n/g, '</p><p style="margin-bottom: 1rem; line-height: 1.6; color: #374151;">')
        .replace(/^/, '<p style="margin-bottom: 1rem; line-height: 1.6; color: #374151;">')
        .replace(/$/, '</p>')
      
      console.log('Fallback HTML:', fallbackHtml)
      return fallbackHtml
    }
  }

  // Export PDF function
  const exportToPDF = () => {
    // Create a new window for printing
    const printWindow = window.open('', '_blank');
    
    if (!printWindow) {
      alert('Please allow pop-ups to export PDF');
      return;
    }

    // Get the current date for the report
    const reportDate = new Date().toLocaleDateString('en-US', {
      year: 'numeric',
      month: 'long',
      day: 'numeric'
    });

    // Get date range info for the report
    const getDateRangeForReport = () => {
      if (startDate && endDate) {
        const startFormatted = new Date(startDate).toLocaleDateString('en-US', {
          year: 'numeric', month: 'long', day: 'numeric'
        });
        const endFormatted = new Date(endDate).toLocaleDateString('en-US', {
          year: 'numeric', month: 'long', day: 'numeric'
        });
        return `${startFormatted} to ${endFormatted}`;
      } else if (startDate) {
        return `From ${new Date(startDate).toLocaleDateString('en-US', {
          year: 'numeric', month: 'long', day: 'numeric'
        })}`;
      } else if (endDate) {
        return `Until ${new Date(endDate).toLocaleDateString('en-US', {
          year: 'numeric', month: 'long', day: 'numeric'
        })}`;
      } else {
        return 'All Time';
      }
    };

    // Create the HTML content for the PDF
    const printContent = `
      <!DOCTYPE html>
      <html>
        <head>
          <title>Team Accomplishments Summary - ${reportDate}</title>
          <style>
            @page {
              margin: 1in;
              size: A4;
            }
            
            body {
              font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
              line-height: 1.6;
              color: #333;
              max-width: none;
              margin: 0;
              padding: 0;
              background: white;
            }
            
            .header {
              border-bottom: 3px solid #0284c7;
              padding-bottom: 20px;
              margin-bottom: 30px;
              page-break-inside: avoid;
            }
            
            .header h1 {
              color: #0284c7;
              margin: 0 0 10px 0;
              font-size: 28px;
              font-weight: 700;
            }
            
            .header .subtitle {
              color: #6b7280;
              margin: 5px 0;
              font-size: 14px;
            }
            
            .header .report-info {
              margin-top: 15px;
              padding: 10px 15px;
              background-color: #f8fafc;
              border-left: 4px solid #0284c7;
              border-radius: 4px;
            }
            
            .header .report-info strong {
              color: #0284c7;
            }
            
            .ai-badge {
              display: inline-flex;
              align-items: center;
              gap: 6px;
              background-color: ${isAISummary ? '#ecfdf5' : '#f1f5f9'};
              color: ${isAISummary ? '#047857' : '#64748b'};
              padding: 6px 12px;
              border-radius: 6px;
              font-size: 12px;
              font-weight: 600;
              border: 1px solid ${isAISummary ? '#d1fae5' : '#e2e8f0'};
              margin-top: 10px;
            }
            
            .summary-content {
              font-size: 14px;
              line-height: 1.7;
            }
            
            .summary-content h1 {
              color: #1e40af;
              font-size: 24px;
              margin: 30px 0 15px 0;
              page-break-after: avoid;
            }
            
            .summary-content h2 {
              color: #1e3a8a;
              font-size: 20px;
              margin: 25px 0 12px 0;
              border-bottom: 2px solid #e5e7eb;
              padding-bottom: 8px;
              page-break-after: avoid;
            }
            
            .summary-content h3 {
              color: #2563eb;
              font-size: 16px;
              margin: 20px 0 10px 0;
              page-break-after: avoid;
            }
            
            .summary-content h4 {
              color: #3b82f6;
              font-size: 14px;
              margin: 15px 0 8px 0;
              page-break-after: avoid;
            }
            
            .summary-content p {
              margin-bottom: 12px;
              orphans: 2;
              widows: 2;
            }
            
            .summary-content ul, .summary-content ol {
              margin: 12px 0;
              padding-left: 25px;
            }
            
            .summary-content li {
              margin-bottom: 6px;
              orphans: 2;
              widows: 2;
            }
            
            .summary-content strong {
              font-weight: 700;
              color: #1f2937;
            }
            
            .summary-content em {
              font-style: italic;
              color: #4b5563;
            }
            
            .summary-content code {
              background-color: #f3f4f6;
              padding: 2px 6px;
              border-radius: 3px;
              font-family: 'Courier New', monospace;
              font-size: 12px;
            }
            
            .summary-content blockquote {
              border-left: 4px solid #3b82f6;
              padding: 15px;
              margin: 15px 0;
              font-style: italic;
              background-color: #f8fafc;
              border-radius: 4px;
            }
            
            .summary-content table {
              width: 100%;
              border-collapse: collapse;
              margin: 15px 0;
              font-size: 13px;
            }
            
            .summary-content th {
              padding: 10px;
              text-align: left;
              font-weight: 600;
              background-color: #f9fafb;
              border: 1px solid #e5e7eb;
            }
            
            .summary-content td {
              padding: 10px;
              border: 1px solid #e5e7eb;
            }
            
            .footer {
              margin-top: 40px;
              padding-top: 20px;
              border-top: 1px solid #e5e7eb;
              font-size: 12px;
              color: #6b7280;
              text-align: center;
              page-break-inside: avoid;
            }
            
            @media print {
              body { print-color-adjust: exact; }
              .header, .summary-content h1, .summary-content h2 { page-break-inside: avoid; }
              .summary-content h1, .summary-content h2, .summary-content h3 { page-break-after: avoid; }
            }
          </style>
        </head>
        <body>
          <div class="header">
            <h1>Team Pulse Agent - Executive Summary</h1>
            <div class="subtitle">Professional Team Accomplishments Report</div>
            <div class="ai-badge">
              <span>${isAISummary ? '✨' : '📝'}</span>
              ${isAISummary ? `Azure OpenAI Enhanced${aiModel ? ` • ${aiModel}` : ''}` : 'Standard Summary'}
            </div>
            <div class="report-info">
              <div><strong>Report Period:</strong> ${getDateRangeForReport()}</div>
              <div><strong>Generated:</strong> ${reportDate}</div>
              <div><strong>Total Accomplishments:</strong> ${filteredAccomplishments.length}</div>
            </div>
          </div>
          
          <div class="summary-content">
            ${renderMarkdown(summaryText)}
          </div>
          
          <div class="footer">
            <div>Generated by Team Pulse Agent • ${reportDate}</div>
            <div>This report contains ${filteredAccomplishments.length} team accomplishments</div>
          </div>
        </body>
      </html>
    `;

    // Write content to the new window
    printWindow.document.write(printContent);
    printWindow.document.close();

    // Wait for content to load, then print
    printWindow.onload = () => {
      setTimeout(() => {
        printWindow.print();
        printWindow.close();
      }, 250);
    };
  };

  // Clear summary
  const clearSummary = () => {
    setSummaryText('')
    setIsAISummary(false)
    setAiModel('')
  }

  // Navigation helper functions
  const scrollToForm = () => {
    setShowAddModal(true);
  };

  const scrollToList = () => {
    listRef.current?.scrollIntoView({ behavior: 'smooth', block: 'start' });
  };

  const scrollToSummary = () => {
    if (filteredAccomplishments.length > 0) {
      aiGenerationRef.current?.scrollIntoView({ behavior: 'smooth', block: 'start' });
    } else {
      // If no accomplishments, still scroll to the section but show a message
      aiGenerationRef.current?.scrollIntoView({ behavior: 'smooth', block: 'start' });
    }
  };

  const clearAllFilters = () => {
    setStartDate('');
    setEndDate('');
    setSearchTerm('');
    setDatePreset('all-time');
  };

  return (
    <>
      <style>
        {`
          .executive-summary-content ul, .executive-summary-content ol {
            margin: 1rem 0;
            padding-left: 1.5rem;
          }
          .executive-summary-content ul li {
            list-style-type: disc;
            margin-bottom: 0.5rem;
          }
          .executive-summary-content ol li {
            list-style-type: decimal;
            margin-bottom: 0.5rem;
          }
          .executive-summary-content p {
            margin-bottom: 1rem;
          }
          .executive-summary-content h1:first-child,
          .executive-summary-content h2:first-child,
          .executive-summary-content h3:first-child {
            margin-top: 0;
          }
          .executive-summary-content code {
            font-family: 'Monaco', 'Menlo', 'Ubuntu Mono', monospace;
          }
          .executive-summary-content pre {
            background-color: #f8f9fa;
            border: 1px solid #e9ecef;
            border-radius: 0.375rem;
            padding: 1rem;
            overflow-x: auto;
            margin: 1rem 0;
          }
          .executive-summary-content a {
            color: #3b82f6;
            text-decoration: underline;
          }
          .executive-summary-content a:hover {
            color: #1d4ed8;
          }
        `}
      </style>
      <main style={{ maxWidth: 800, margin: '40px auto', padding: 16, backgroundColor: '#f8fafc', minHeight: '100vh' }}>
      <header className="app-header">
        <div className="logo-title-container">
          <img 
            src="/Logo.svg" 
            alt="Team Pulse Agent Logo" 
            className="app-logo"
          />
          <div>
            <h1 style={{ margin: 0 }}>Team Pulse Agent</h1>
            <p style={{ margin: '5px 0 0 0' }}>
              Track team accomplishments and generate summaries for meetings and reviews.
            </p>
          </div>
        </div>
        <UserMenu onOpenSettings={() => setShowSettingsModal(true)} />
      </header>

      {/* Enhanced Navigation */}
      <Navigation
        totalAccomplishments={accomplishments.length}
        filteredAccomplishments={filteredAccomplishments.length}
        searchTerm={searchTerm}
        onClearFilters={clearAllFilters}
        onScrollToForm={scrollToForm}
        onScrollToList={scrollToList}
        onScrollToSummary={scrollToSummary}
      />

      {/* Filtering and List View */}
      <section ref={listRef} style={{ marginBottom: 30, backgroundColor: 'white', borderRadius: 8, padding: 24, boxShadow: '0 1px 3px rgba(0, 0, 0, 0.1)' }}>
        {/* Section Header */}
        <div style={{ 
          display: 'flex', 
          justifyContent: 'space-between', 
          alignItems: 'center', 
          marginBottom: 24,
          paddingBottom: 16,
          borderBottom: '2px solid #e5e7eb'
        }}>
          <div>
            <h2 style={{ 
              margin: 0, 
              fontSize: '1.5rem', 
              fontWeight: '700', 
              color: '#1f2937',
              lineHeight: '1.2'
            }}>
              Team Accomplishments
            </h2>
            {searchTerm && (
              <p style={{ 
                margin: '4px 0 0 0', 
                fontSize: '0.9rem', 
                color: '#6b7280',
                fontWeight: '500'
              }}>
                {filteredAccomplishments.length} results for "{searchTerm}"
              </p>
            )}
          </div>
          
          {/* Delete All button if there are accomplishments */}
          {accomplishments.length > 0 && (
            <button
              onClick={handleDeleteAll}
              style={{
                backgroundColor: '#ef4444',
                color: 'white',
                padding: '8px 16px',
                fontSize: '0.9rem',
                border: 'none',
                borderRadius: '6px',
                cursor: 'pointer',
                display: 'flex',
                alignItems: 'center',
                gap: '6px',
                fontWeight: '500',
                transition: 'all 0.2s ease',
                boxShadow: '0 1px 3px rgba(0, 0, 0, 0.1)'
              }}
              onMouseEnter={(e) => {
                e.target.style.backgroundColor = '#dc2626';
                e.target.style.transform = 'translateY(-1px)';
                e.target.style.boxShadow = '0 4px 6px rgba(0, 0, 0, 0.15)';
              }}
              onMouseLeave={(e) => {
                e.target.style.backgroundColor = '#ef4444';
                e.target.style.transform = 'translateY(0)';
                e.target.style.boxShadow = '0 1px 3px rgba(0, 0, 0, 0.1)';
              }}
            >
              <span style={{ fontSize: '1rem' }}>🗑️</span>
              Delete All
            </button>
          )}
        </div>

        {/* Filters Section */}
        <div style={{ 
          backgroundColor: '#f8fafc', 
          padding: '20px', 
          borderRadius: '8px', 
          marginBottom: '24px',
          border: '1px solid #e2e8f0'
        }}>
          {/* Filter Header */}
          <div style={{ 
            display: 'flex', 
            alignItems: 'center', 
            marginBottom: '16px',
            gap: '8px'
          }}>
            <h3 style={{ 
              margin: 0, 
              fontSize: '1.1rem', 
              fontWeight: '600', 
              color: '#374151'
            }}>
              🔍 Filters & Search
            </h3>
            {(startDate || endDate || searchTerm) && (
              <button
                onClick={() => {
                  setStartDate('')
                  setEndDate('')
                  setSearchTerm('')
                  setDatePreset('all-time')
                }}
                style={{
                  backgroundColor: '#6b7280',
                  color: 'white',
                  padding: '4px 8px',
                  border: 'none',
                  borderRadius: '4px',
                  cursor: 'pointer',
                  fontSize: '0.8rem',
                  fontWeight: '500',
                  display: 'flex',
                  alignItems: 'center',
                  gap: '4px',
                  transition: 'all 0.2s ease'
                }}
                onMouseEnter={(e) => e.target.style.backgroundColor = '#4b5563'}
                onMouseLeave={(e) => e.target.style.backgroundColor = '#6b7280'}
              >
                <span>×</span>
                Clear All
              </button>
            )}
          </div>

          {/* Search Bar */}
          <div style={{ marginBottom: '16px' }}>
            <div className="search-container" style={{ position: 'relative', maxWidth: '400px' }}>
              <input
                type="text"
                placeholder="Search accomplishments..."
                value={searchTerm}
                onChange={(e) => setSearchTerm(e.target.value)}
                style={{
                  width: '100%',
                  padding: '12px 16px',
                  paddingRight: searchTerm ? '40px' : '16px',
                  borderRadius: '6px',
                  border: '1px solid #d1d5db',
                  fontSize: '0.95rem',
                  outline: 'none',
                  transition: 'all 0.2s ease',
                  backgroundColor: 'white'
                }}
                onFocus={(e) => {
                  e.target.style.borderColor = '#3b82f6';
                  e.target.style.boxShadow = '0 0 0 3px rgba(59, 130, 246, 0.1)';
                }}
                onBlur={(e) => {
                  e.target.style.borderColor = '#d1d5db';
                  e.target.style.boxShadow = 'none';
                }}
              />
              {searchTerm && (
                <button 
                  onClick={() => setSearchTerm('')}
                  style={{
                    position: 'absolute',
                    right: '8px',
                    top: '50%',
                    transform: 'translateY(-50%)',
                    background: 'none',
                    border: 'none',
                    cursor: 'pointer',
                    fontSize: '1.2rem',
                    color: '#6b7280',
                    padding: '4px',
                    borderRadius: '4px',
                    display: 'flex',
                    alignItems: 'center',
                    justifyContent: 'center'
                  }}
                  onMouseEnter={(e) => e.target.style.backgroundColor = '#f3f4f6'}
                  onMouseLeave={(e) => e.target.style.backgroundColor = 'transparent'}
                >
                  ×
                </button>
              )}
            </div>
          </div>

          {/* Date Filters Row */}
          <div style={{ 
            display: 'grid', 
            gridTemplateColumns: 'auto 1fr auto auto', 
            gap: '16px', 
            alignItems: 'end',
            '@media (max-width: 768px)': {
              gridTemplateColumns: '1fr',
              gap: '12px'
            }
          }}>
            {/* Quick Filter Dropdown */}
            <div>
              <label htmlFor="datePreset" style={{ 
                display: 'block',
                marginBottom: '6px',
                fontSize: '0.9rem',
                fontWeight: '500',
                color: '#374151'
              }}>
                Quick Filter
              </label>
              <select
                id="datePreset"
                value={datePreset}
                onChange={(e) => handleDatePresetChange(e.target.value)}
                style={{ 
                  padding: '10px 12px', 
                  borderRadius: '6px', 
                  border: '1px solid #d1d5db',
                  backgroundColor: 'white',
                  fontSize: '0.9rem',
                  fontWeight: '500',
                  color: '#374151',
                  minWidth: '180px',
                  cursor: 'pointer',
                  outline: 'none',
                  transition: 'all 0.2s ease'
                }}
                onFocus={(e) => {
                  e.target.style.borderColor = '#3b82f6';
                  e.target.style.boxShadow = '0 0 0 3px rgba(59, 130, 246, 0.1)';
                }}
                onBlur={(e) => {
                  e.target.style.borderColor = '#d1d5db';
                  e.target.style.boxShadow = 'none';
                }}
              >
                <option value="all-time">🌍 All Time</option>
                <option value="current-quarter">📅 Current Quarter</option>
                <option value="last-quarter">📆 Last Quarter</option>
                <option value="last-semester">🗓️ Last Semester (6mo)</option>
                <option value="custom">⚙️ Custom Range</option>
              </select>
            </div>

            {/* From Date */}
            <div>
              <label htmlFor="startDate" style={{ 
                display: 'block',
                marginBottom: '6px',
                fontSize: '0.9rem',
                fontWeight: '500',
                color: '#374151'
              }}>
                From Date
              </label>
              <input
                id="startDate"
                type="date"
                value={startDate}
                onChange={(e) => setStartDate(e.target.value)}
                style={{ 
                  padding: '10px 12px', 
                  borderRadius: '6px', 
                  border: datePreset === 'custom' ? '2px solid #3b82f6' : '1px solid #d1d5db',
                  backgroundColor: datePreset === 'custom' ? '#eff6ff' : 'white',
                  fontSize: '0.9rem',
                  outline: 'none',
                  transition: 'all 0.2s ease'
                }}
                onFocus={(e) => {
                  if (datePreset !== 'custom') {
                    e.target.style.borderColor = '#3b82f6';
                    e.target.style.boxShadow = '0 0 0 3px rgba(59, 130, 246, 0.1)';
                  }
                }}
                onBlur={(e) => {
                  if (datePreset !== 'custom') {
                    e.target.style.borderColor = '#d1d5db';
                    e.target.style.boxShadow = 'none';
                  }
                }}
              />
            </div>

            {/* To Date */}
            <div>
              <label htmlFor="endDate" style={{ 
                display: 'block',
                marginBottom: '6px',
                fontSize: '0.9rem',
                fontWeight: '500',
                color: '#374151'
              }}>
                To Date
              </label>
              <input
                id="endDate"
                type="date"
                value={endDate}
                onChange={(e) => setEndDate(e.target.value)}
                style={{ 
                  padding: '10px 12px', 
                  borderRadius: '6px', 
                  border: datePreset === 'custom' ? '2px solid #3b82f6' : '1px solid #d1d5db',
                  backgroundColor: datePreset === 'custom' ? '#eff6ff' : 'white',
                  fontSize: '0.9rem',
                  outline: 'none',
                  transition: 'all 0.2s ease'
                }}
                onFocus={(e) => {
                  if (datePreset !== 'custom') {
                    e.target.style.borderColor = '#3b82f6';
                    e.target.style.boxShadow = '0 0 0 3px rgba(59, 130, 246, 0.1)';
                  }
                }}
                onBlur={(e) => {
                  if (datePreset !== 'custom') {
                    e.target.style.borderColor = '#d1d5db';
                    e.target.style.boxShadow = 'none';
                  }
                }}
              />
            </div>
          </div>

          {/* Date Range Info */}
          {datePreset && datePreset !== 'all-time' && datePreset !== 'custom' && (
            <div style={{ 
              marginTop: '12px',
              padding: '8px 12px',
              backgroundColor: '#e0f2fe',
              borderRadius: '6px',
              border: '1px solid #b3e5fc'
            }}>
              <div style={{ 
                fontSize: '0.85rem', 
                color: '#0277bd', 
                fontWeight: '500',
                display: 'flex',
                alignItems: 'center',
                gap: '6px'
              }}>
                <span>📅</span>
                {datePreset === 'current-quarter' && `Current Quarter: ${formatDateForDisplay(startDate)} to ${formatDateForDisplay(endDate)}`}
                {datePreset === 'last-quarter' && `Last Quarter: ${formatDateForDisplay(startDate)} to ${formatDateForDisplay(endDate)}`}
                {datePreset === 'last-semester' && `Last 6 Months: ${formatDateForDisplay(startDate)} to ${formatDateForDisplay(endDate)}`}
              </div>
            </div>
          )}
        </div>
        
        {filteredAccomplishments.length > 0 ? (
          <div>
            <div style={{ 
              display: 'flex', 
              justifyContent: 'space-between', 
              alignItems: 'center', 
              marginBottom: 16,
              padding: '12px 16px',
              backgroundColor: '#f8fafc',
              borderRadius: '6px',
              border: '1px solid #e2e8f0'
            }}>
              <span style={{
                fontSize: '0.95rem',
                color: '#374151',
                fontWeight: '500'
              }}>
                Showing {Math.min(visibleItems, filteredAccomplishments.length)} of {filteredAccomplishments.length} accomplishments
              </span>
            </div>
            
            <ul className="accomplishments-list" style={{ 
              padding: 0, 
              listStyleType: 'none'
            }}>
              {filteredAccomplishments.slice(0, visibleItems).map(acc => (
                <li 
                  key={acc.id} 
                  style={{ 
                    marginBottom: 10, 
                    padding: 15, 
                    backgroundColor: 
                      acc.category === 'Feature' ? '#e3f2fd' : 
                      acc.category === 'Bug Fix' ? '#ffebee' : 
                      acc.category === 'Process' ? '#e8f5e9' : 
                      '#fff3e0',
                    borderRadius: 5,
                    border: '1px solid #ddd'
                  }}
                >
                  <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start' }}>
                    <h3 style={{ margin: '0 0 5px 0' }}>{acc.title}</h3>
                    <div style={{ display: 'flex', gap: 5 }}>
                      <button
                        onClick={() => handleEdit(acc)}
                        style={{
                          backgroundColor: '#2196F3',
                          color: 'white',
                          padding: '4px 8px',
                          fontSize: '0.8rem',
                          border: 'none',
                          borderRadius: 4,
                          cursor: 'pointer'
                        }}
                      >
                        Edit
                      </button>
                      <button
                        onClick={() => handleDelete(acc.id)}
                        style={{
                          backgroundColor: '#f44336',
                          color: 'white',
                          padding: '4px 8px',
                          fontSize: '0.8rem',
                          border: 'none',
                          borderRadius: 4,
                          cursor: 'pointer'
                        }}
                      >
                        Delete
                      </button>
                    </div>
                  </div>
                  <div style={{ display: 'flex', justifyContent: 'space-between', marginBottom: 5 }}>
                    <span className={`category-badge category-${acc.category.replace(' ', '-')}`}>{acc.category}</span>
                    <span>{acc.date}</span>
                  </div>
                  {acc.contributors && (
                    <div style={{ marginBottom: 8, fontSize: '0.9rem', color: '#4b5563' }}>
                      <strong>Contributors:</strong> {acc.contributors}
                    </div>
                  )}
                  <p style={{ margin: '5px 0 0 0' }}>{acc.description}</p>
                </li>
              ))}
              {visibleItems < filteredAccomplishments.length && (
                <li 
                  ref={loaderRef}
                  style={{ 
                    textAlign: 'center', 
                    padding: '10px',
                    borderRadius: 5
                  }}
                >
                  {isLoading ? (
                    <div className="loading-indicator">
                      <div style={{ 
                        display: 'inline-block',
                        width: '20px',
                        height: '20px',
                        border: '3px solid rgba(0, 0, 0, 0.1)',
                        borderRadius: '50%',
                        borderTopColor: '#3498db',
                        animation: 'spin 1s ease-in-out infinite'
                      }}></div>
                      <span style={{ marginLeft: '10px' }}>Loading more...</span>
                    </div>
                  ) : (
                    <button
                      onClick={() => {
                        setIsLoading(true);
                        setTimeout(() => {
                          setVisibleItems(prev => Math.min(prev + 3, filteredAccomplishments.length));
                          setIsLoading(false);
                        }, 300);
                      }}
                      style={{
                        backgroundColor: '#f0f0f0',
                        color: '#333',
                        padding: '8px 15px',
                        border: 'none',
                        borderRadius: '4px',
                        cursor: 'pointer',
                        fontSize: '0.9rem'
                      }}
                    >
                      Load More
                    </button>
                  )}
                </li>
              )}
            </ul>
            
            {/* AI Summary Generation Section */}
            <div 
              ref={aiGenerationRef}
              style={{ 
                marginTop: '24px',
                padding: '20px',
                backgroundColor: '#f0f9ff',
                borderRadius: '8px',
                border: '1px solid #bae6fd'
              }}
            >
              <div style={{ 
                display: 'flex', 
                alignItems: 'center', 
                marginBottom: '16px',
                gap: '8px'
              }}>
                <h3 style={{ 
                  margin: 0, 
                  fontSize: '1.1rem', 
                  fontWeight: '600', 
                  color: '#0369a1',
                  display: 'flex',
                  alignItems: 'center',
                  gap: '8px'
                }}>
                  <span style={{ fontSize: '1.2rem' }}>✨</span>
                  AI-Powered Summary Generation
                </h3>
              </div>
              
              <p style={{ 
                margin: '0 0 16px 0', 
                fontSize: '0.9rem', 
                color: '#0369a1',
                lineHeight: '1.5'
              }}>
                Generate an executive-ready summary of your team's accomplishments using Azure OpenAI
              </p>
              
              {/* Custom Formatting Instructions (Optional) */}
              <div style={{ marginBottom: '20px' }}>
                <label 
                  htmlFor="custom-format"
                  style={{ 
                    display: 'block',
                    marginBottom: '8px',
                    fontSize: '0.9rem',
                    fontWeight: '500',
                    color: '#0369a1'
                  }}
                >
                  Custom Formatting Preferences <span style={{ color: '#64748b', fontWeight: 'normal', fontSize: '0.85rem' }}>(Optional)</span>
                </label>
                <textarea
                  id="custom-format"
                  value={customFormat}
                  onChange={(e) => setCustomFormat(e.target.value)}
                  placeholder="Default: Executive Overview → Key Accomplishments → Category Insights → Strategic Outlook&#10;&#10;Add your preferences here, e.g.:&#10;• Include specific metrics and KPIs&#10;• Use bullet points for each section&#10;• Add a timeline of major milestones&#10;• Highlight team collaboration efforts&#10;• Focus on customer impact"
                  rows={3}
                  aria-label="Custom formatting preferences for AI summary"
                  style={{
                    width: '100%',
                    maxWidth: '100%',
                    boxSizing: 'border-box',
                    padding: '12px',
                    borderRadius: '6px',
                    border: '1px solid #7dd3fc',
                    backgroundColor: 'white',
                    fontSize: '0.85rem',
                    color: '#334155',
                    fontFamily: 'inherit',
                    resize: 'vertical',
                    outline: 'none',
                    transition: 'all 0.2s ease',
                    lineHeight: '1.5',
                    minHeight: '80px'
                  }}
                  onFocus={(e) => {
                    e.target.style.borderColor = '#0284c7';
                    e.target.style.boxShadow = '0 0 0 3px rgba(14, 165, 233, 0.1)';
                  }}
                  onBlur={(e) => {
                    e.target.style.borderColor = '#7dd3fc';
                    e.target.style.boxShadow = 'none';
                  }}
                />
              </div>
              
              <div style={{ 
                display: 'flex', 
                alignItems: 'center', 
                gap: '16px',
                flexWrap: 'wrap'
              }}>
                {/* Model Selection */}
                <div style={{ minWidth: '200px' }}>
                  <label 
                    htmlFor="model-select"
                    style={{ 
                      display: 'block',
                      marginBottom: '6px',
                      fontSize: '0.9rem',
                      fontWeight: '500',
                      color: '#0369a1'
                    }}
                  >
                    AI Model
                  </label>
                  <select 
                    id="model-select"
                    value={selectedModel} 
                    onChange={(e) => setSelectedModel(e.target.value)}
                    style={{
                      width: '100%',
                      padding: '10px 12px',
                      borderRadius: '6px',
                      border: '1px solid #7dd3fc',
                      backgroundColor: 'white',
                      fontSize: '0.9rem',
                      fontWeight: '500',
                      color: '#0369a1',
                      cursor: 'pointer',
                      outline: 'none',
                      transition: 'all 0.2s ease'
                    }}
                    onFocus={(e) => {
                      e.target.style.borderColor = '#0284c7';
                      e.target.style.boxShadow = '0 0 0 3px rgba(14, 165, 233, 0.1)';
                    }}
                    onBlur={(e) => {
                      e.target.style.borderColor = '#7dd3fc';
                      e.target.style.boxShadow = 'none';
                    }}
                  >
                    <option value="gpt-4.1">🎯 GPT-4.1</option>
                  </select>
                </div>
                
                {/* Generate Button */}
                <div style={{ flex: '1', minWidth: '200px' }}>
                  <div style={{ height: '22px' }}></div> {/* Spacer to align with label */}
                  <button 
                    onClick={generateSummary}
                    disabled={isSummaryLoading || filteredAccomplishments.length === 0}
                    style={{ 
                      width: '100%',
                      backgroundColor: 
                        isSummaryLoading ? '#94a3b8' : 
                        filteredAccomplishments.length === 0 ? '#e5e7eb' : '#0284c7', 
                      color: filteredAccomplishments.length === 0 ? '#9ca3af' : 'white', 
                      padding: '12px 20px', 
                      border: 'none', 
                      borderRadius: '6px', 
                      cursor: 
                        isSummaryLoading || filteredAccomplishments.length === 0 ? 'not-allowed' : 'pointer',
                      display: 'flex',
                      alignItems: 'center',
                      justifyContent: 'center',
                      gap: '10px',
                      fontSize: '0.95rem',
                      fontWeight: '600',
                      opacity: isSummaryLoading ? 0.8 : 1,
                      boxShadow: 
                        isSummaryLoading || filteredAccomplishments.length === 0 ? 'none' : '0 2px 4px rgba(2, 132, 199, 0.2)',
                      transition: 'all 0.2s ease',
                      minHeight: '44px'
                    }}
                    onMouseEnter={(e) => {
                      if (!isSummaryLoading && filteredAccomplishments.length > 0) {
                        e.target.style.backgroundColor = '#0369a1';
                        e.target.style.transform = 'translateY(-1px)';
                        e.target.style.boxShadow = '0 4px 8px rgba(2, 132, 199, 0.3)';
                      }
                    }}
                    onMouseLeave={(e) => {
                      if (!isSummaryLoading && filteredAccomplishments.length > 0) {
                        e.target.style.backgroundColor = '#0284c7';
                        e.target.style.transform = 'translateY(0)';
                        e.target.style.boxShadow = '0 2px 4px rgba(2, 132, 199, 0.2)';
                      }
                    }}
                  >
                    {isSummaryLoading ? (
                      <>
                        <div style={{ 
                          display: 'inline-block',
                          width: '18px',
                          height: '18px',
                          border: '2px solid rgba(255, 255, 255, 0.3)',
                          borderRadius: '50%',
                          borderTopColor: 'white',
                          animation: 'spin 1s ease-in-out infinite'
                        }}></div>
                        Generating Summary...
                      </>
                    ) : filteredAccomplishments.length === 0 ? (
                      <>
                        <span style={{ fontSize: '18px' }}>📝</span>
                        Add accomplishments to generate summary
                      </>
                    ) : (
                      <>
                        <span style={{ fontSize: '18px' }}>🎯</span>
                        Generate Executive Summary
                      </>
                    )}
                  </button>
                </div>
              </div>
              
              {/* Additional Info */}
              <div style={{ 
                marginTop: '12px',
                padding: '8px 12px',
                backgroundColor: 'white',
                borderRadius: '6px',
                border: '1px solid #e0f2fe'
              }}>
                <div style={{ 
                  fontSize: '0.8rem', 
                  color: '#0369a1',
                  display: 'flex',
                  alignItems: 'center',
                  gap: '6px'
                }}>
                  <span>💡</span>
                  <span>
                    {filteredAccomplishments.length === 0 
                      ? "Add team accomplishments to unlock AI-powered executive summary generation."
                      : `Ready to generate a professional summary from ${filteredAccomplishments.length} accomplishment${filteredAccomplishments.length === 1 ? '' : 's'} for executive reporting and team reviews.`
                    }
                  </span>
                </div>
              </div>
            </div>
          </div>
        ) : (
          <div style={{ 
            textAlign: 'center', 
            padding: '40px 20px', 
            backgroundColor: '#f9fafb', 
            borderRadius: '8px',
            border: '2px dashed #d1d5db'
          }}>
            {searchTerm ? (
              <div>
                <div style={{ fontSize: '3rem', marginBottom: '16px' }}>🔍</div>
                <h3 style={{ 
                  margin: '0 0 8px 0', 
                  color: '#374151', 
                  fontSize: '1.1rem',
                  fontWeight: '600'
                }}>
                  No matching accomplishments found
                </h3>
                <p style={{ 
                  margin: 0, 
                  color: '#6b7280', 
                  fontSize: '0.95rem'
                }}>
                  No accomplishments match your search for "<strong>{searchTerm}</strong>". 
                  Try a different search term or clear the search.
                </p>
              </div>
            ) : (
              <div>
                <div style={{ fontSize: '3rem', marginBottom: '16px' }}>🎯</div>
                <h3 style={{ 
                  margin: '0 0 8px 0', 
                  color: '#374151', 
                  fontSize: '1.1rem',
                  fontWeight: '600'
                }}>
                  No accomplishments yet
                </h3>
                <p style={{ 
                  margin: 0, 
                  color: '#6b7280', 
                  fontSize: '0.95rem'
                }}>
                  Start tracking your team's achievements by adding your first accomplishment!
                </p>
              </div>
            )}
          </div>
        )}
      </section>

      {/* Summary Display */}
      {summaryText && (
        <section ref={summaryRef} style={{ 
          marginBottom: 30, 
          padding: 25, 
          backgroundColor: 'white', 
          borderRadius: 8, 
          border: '1px solid #d1d5db',
          boxShadow: '0 4px 6px rgba(0, 0, 0, 0.05)'
        }}>
          <div style={{ 
            display: 'flex', 
            justifyContent: 'space-between', 
            alignItems: 'center', 
            marginBottom: 15,
            borderBottom: '1px solid #e5e7eb',
            paddingBottom: 15
          }}>
            <h2 style={{ margin: 0, color: '#1e3a8a' }}>Executive Summary</h2>
            <div>
              <button
                onClick={() => {
                  navigator.clipboard.writeText(summaryText);
                  alert('Summary copied to clipboard!');
                }}
                style={{
                  backgroundColor: '#4b5563',
                  color: 'white',
                  padding: '8px 12px',
                  border: 'none',
                  borderRadius: 4,
                  cursor: 'pointer',
                  marginRight: 8,
                  fontSize: '0.9rem'
                }}
              >
                Copy
              </button>
              <button
                onClick={exportToPDF}
                style={{
                  backgroundColor: '#0284c7',
                  color: 'white',
                  padding: '8px 12px',
                  border: 'none',
                  borderRadius: 4,
                  cursor: 'pointer',
                  marginRight: 8,
                  fontSize: '0.9rem'
                }}
              >
                Export PDF
              </button>
              <button
                onClick={clearSummary}
                style={{
                  backgroundColor: '#ef4444',
                  color: 'white',
                  padding: '8px 12px',
                  border: 'none',
                  borderRadius: 4,
                  cursor: 'pointer',
                  fontSize: '0.9rem'
                }}
              >
                Close
              </button>
            </div>
          </div>
          <div className="executive-summary-content" style={{ 
            fontFamily: 'system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif', 
            lineHeight: 1.6,
            color: '#374151',
            position: 'relative'
          }}>
            {/* AI badge */}
            <div style={{
              position: 'absolute',
              top: '0',
              right: '0',
              backgroundColor: isAISummary ? '#ecfdf5' : '#f1f5f9',
              color: isAISummary ? '#047857' : '#64748b',
              padding: '6px 10px',
              borderRadius: '4px',
              fontSize: '0.8rem',
              fontWeight: 'bold',
              display: 'flex',
              alignItems: 'center',
              gap: '6px',
              border: isAISummary ? '1px solid #d1fae5' : '1px solid #e2e8f0',
              boxShadow: '0 1px 2px rgba(0, 0, 0, 0.05)'
            }}>
              <span style={{ fontSize: '1rem' }}>{isAISummary ? '✨' : '📝'}</span>
              {isAISummary ? `Azure OpenAI Enhanced${aiModel ? ` • ${aiModel}` : ''}` : 'Standard Summary'}
            </div>
            
            <div 
              dangerouslySetInnerHTML={{ __html: renderMarkdown(summaryText) }}
              style={{
                fontFamily: 'system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif', 
                lineHeight: 1.6,
                color: '#374151',
                position: 'relative',
                paddingTop: '2rem' // Add space for the AI badge
              }}
              className="executive-summary-content"
            />
          </div>
        </section>
      )}

      {/* Delete All Confirmation Modal */}
      {showDeleteConfirm && (
        <div style={{
          position: 'fixed',
          top: 0,
          left: 0,
          right: 0,
          bottom: 0,
          backgroundColor: 'rgba(0, 0, 0, 0.5)',
          display: 'flex',
          justifyContent: 'center',
          alignItems: 'center',
          zIndex: 1000
        }}>
          <div style={{
            backgroundColor: 'white',
            padding: 20,
            borderRadius: 8,
            maxWidth: 500,
            width: '90%',
            boxShadow: '0 4px 6px rgba(0, 0, 0, 0.1)'
          }}>
            <h3 style={{ marginTop: 0, color: '#ef4444' }}>Delete All Accomplishments?</h3>
            <p>
              Are you sure you want to delete all {accomplishments.length} accomplishments? This action cannot be undone.
            </p>
            <div style={{
              display: 'flex',
              justifyContent: 'flex-end',
              gap: 10,
              marginTop: 20
            }}>
              <button
                onClick={cancelDeleteAll}
                style={{
                  backgroundColor: '#f3f4f6',
                  color: '#374151',
                  padding: '8px 16px',
                  border: 'none',
                  borderRadius: 4,
                  cursor: 'pointer'
                }}
              >
                Cancel
              </button>
              <button
                onClick={confirmDeleteAll}
                style={{
                  backgroundColor: '#ef4444',
                  color: 'white',
                  padding: '8px 16px',
                  border: 'none',
                  borderRadius: 4,
                  cursor: 'pointer'
                }}
              >
                Delete All
              </button>
            </div>
          </div>
        </div>
      )}

      {/* Add Accomplishment Modal */}
      {showAddModal && (
        <Modal
          isOpen={showAddModal}
          onClose={handleCancelEdit}
          title={isEditing ? 'Edit Accomplishment' : 'Add Team Accomplishment'}
          size="medium"
        >
          <AddAccomplishmentForm
            title={title}
            setTitle={setTitle}
            date={date}
            setDate={setDate}
            category={category}
            setCategory={setCategory}
            description={description}
            setDescription={setDescription}
            contributors={contributors}
            setContributors={setContributors}
            onSubmit={handleSubmit}
            onCancel={handleCancelEdit}
            isEditing={isEditing}
          />
        </Modal>
      )}

      {/* Settings Modal */}
      {showSettingsModal && (
        <SettingsModal
          isOpen={showSettingsModal}
          onClose={() => setShowSettingsModal(false)}
          storageType={storageType}
          sharedFolderPath={sharedFolderPath}
          isSharedFolderConnected={isSharedFolderConnected}
          isLoading={isStorageLoading}
          onStorageTypeChange={handleStorageTypeChange}
          onSharedFolderChange={handleSharedFolderChange}
          onFolderSelect={handleFolderSelect}
          onTestConnection={async () => {
            try {
              setIsStorageLoading(true)
              const isConnected = await storageManager.testSharedFolderConnection()
              setIsSharedFolderConnected(isConnected)
              alert(isConnected ? 'Shared folder connection successful!' : 'Shared folder connection failed. Please check your settings.')
            } catch (error) {
              console.error('Connection test failed:', error)
              alert('Connection test failed. Please try again.')
            } finally {
              setIsStorageLoading(false)
            }
          }}
        />
      )}
    </main>
    </>
  )
}

export default function App() {
  return (
    <MsalProvider instance={msalInstance}>
      <AuthProvider>
        <TeamPulseApp />
      </AuthProvider>
    </MsalProvider>
  );
}
